namespace Mohist.Server.Sessions.Grains;

[GenerateSerializer]
public sealed record AgentSessionInfo(
    [property: Id(0)] string Id,
    [property: Id(1)] string? RunnerId,
    [property: Id(2)] string? AgentSessionId,
    [property: Id(3)] string Status,
    [property: Id(4)] string? Model,
    [property: Id(5)] string? WorkDir,
    [property: Id(6)] string CreatedAt,
    [property: Id(7)] string? StartedAt,
    [property: Id(8)] string? LastDataAt,
    [property: Id(9)] string? ResolvedModel,
    [property: Id(10)] long? InputTokens,
    [property: Id(11)] long? OutputTokens,
    [property: Id(12)] long? TotalTokens,
    [property: Id(13)] long? CachedReadTokens,
    [property: Id(14)] long? ThoughtTokens,
    [property: Id(15)] double? CostAmount,
    [property: Id(16)] string? CostCurrency,
    [property: Id(17)] long? ContextWindowUsed,
    [property: Id(18)] long? ContextWindowSize,
    [property: Id(19)] string? FailureCategory,
    [property: Id(20)] int? ToolCallCount,
    [property: Id(21)] int? ToolErrorCount,
    [property: Id(22)] string? Runtime,
    [property: Id(23)] long? CachedWriteTokens,
    [property: Id(24)] long BindingEpoch = 0,
    [property: Id(25)] string? LastTerminalStatus = null,
    [property: Id(28)] string? AppliedReasoningEffort = null,
    [property: Id(29)] long ContextGeneration = 1,
    [property: Id(30)] int UnresolvedPreviousCount = 0,
    [property: Id(31)] string? NextAction = null);
