// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Mohist.Server.Infrastructure.Data.Migrations;

[DbContext(typeof(Mohist.Server.Infrastructure.Data.Db.MohistDbContext))]
[Migration("20260726111353_AddAgentSessionStatusActivityProjection")]
partial class AddAgentSessionStatusActivityProjection
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        MohistDbContextModelSnapshot.BuildModelCore(modelBuilder);
    }
}