// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Mohist.Server.Infrastructure.Data.Db;

#nullable disable

namespace Mohist.Server.Infrastructure.Data.Migrations;

[DbContext(typeof(MohistDbContext))]
[Migration("20260906000000_AddWorkflowBlockedAttentionProjection")]
partial class AddWorkflowBlockedAttentionProjection
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder) => MohistDbContextModelSnapshot.BuildModelCore(modelBuilder);
}
