// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Mohist.Server.Infrastructure.Data.Db;

#nullable disable

namespace Mohist.Server.Infrastructure.Data.Migrations;

partial class AddWorkspace
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder) => MohistDbContextModelSnapshot.BuildModelCore(modelBuilder);
}
