// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Mohist.Server.Infrastructure.Data.Db;

#nullable disable

namespace Mohist.Server.Infrastructure.Data.Migrations;

[DbContext(typeof(MohistDbContext))]
partial class AgentJobOwnerLedger
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        MohistDbContextModelSnapshot.BuildModelCore(modelBuilder);
    }
}