// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore;
using Mohist.Server.Infrastructure.Data.Db;

#nullable disable

namespace Mohist.Server.Infrastructure.Data.Migrations;

[DbContext(typeof(MohistDbContext))]
[Migration("20260731110000_AddSlackInboxRoutes")]
partial class AddSlackInboxRoutes
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder) => MohistDbContextModelSnapshot.BuildModelCore(modelBuilder);
}
