// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mohist.Server.Infrastructure.Data.Db;

#nullable disable

namespace Mohist.Server.Infrastructure.Data.Migrations
{
    [DbContext(typeof(MohistDbContext))]
    [Migration("20260605025642_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Epic.EpicCounterRow", b =>
                {
                    b.Property<string>("ProjectId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("Next")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProjectId");

                    b.ToTable("EpicCounters");
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Epic.EpicIssueRow", b =>
                {
                    b.Property<string>("EpicId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("IssueId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("IssueNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("EpicId", "IssueId");

                    b.HasIndex("ProjectId", "IssueId")
                        .IsUnique();

                    b.HasIndex("ProjectId", "IssueNumber");

                    b.ToTable("EpicIssues");
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Epic.EpicRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Number");

                    b.HasIndex("ProjectId", "Status", "CreatedAt");

                    b.ToTable("Epics");
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Events.EventRow", b =>
                {
                    b.Property<string>("Source")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("JSON");

                    b.Property<string>("SpecVersion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Time")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Source", "Id");

                    b.HasIndex("Type", "Source", "Id");

                    b.ToTable("Events", (string)null);
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Issue.IssueCommentRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("IssueId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("IssueNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "IssueNumber", "CreatedAt");

                    b.ToTable("IssueComments");
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Issue.IssueCounterRow", b =>
                {
                    b.Property<string>("ProjectId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("Next")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProjectId");

                    b.ToTable("IssueCounters");
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Issue.IssuePrerequisiteRow", b =>
                {
                    b.Property<string>("ProjectId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("IssueNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrerequisiteNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("ProjectId", "IssueNumber", "PrerequisiteNumber");

                    b.ToTable("IssuePrerequisites");
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Issue.IssueRow", b =>
                {
                    b.Property<string>("IssueId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Number")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("INTEGER")
                        .HasComputedColumnSql("json_extract(State, '$.Number')", true);

                    b.Property<int?>("ParentIssueNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProjectId")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasComputedColumnSql("json_extract(State, '$.ProjectId')", true);

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkflowRunId")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasComputedColumnSql("json_extract(State, '$.WorkflowRunId')", true);

                    b.HasKey("IssueId");

                    b.HasIndex("WorkflowRunId");

                    b.HasIndex("ProjectId", "Number")
                        .IsUnique();

                    b.ToTable("Issues", (string)null);
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Project.ProjectRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseBranch")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RepositoriesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Sessions.AgentSessionRuntimeEventRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgentSessionId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("IssueNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Stage")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkType")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkflowRunId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "Sequence")
                        .IsUnique();

                    b.HasIndex("ProjectId", "IssueNumber", "Id");

                    b.HasIndex("WorkflowRunId", "SessionName", "Sequence");

                    b.ToTable("AgentSessionRuntimeEvents", (string)null);
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Sessions.AgentSessionRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentSessionId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("IssueNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastDataAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("RunnerId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Stage")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkType")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkflowRunId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgentSessionId");

                    b.HasIndex("WorkflowRunId", "SessionName")
                        .IsUnique();

                    b.HasIndex("WorkflowRunId", "WorkId");

                    b.HasIndex("ProjectId", "IssueNumber", "CreatedAt");

                    b.HasIndex("ProjectId", "Status", "CreatedAt");

                    b.ToTable("AgentSessions", (string)null);
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Workflow.Prompts.ProjectPromptTemplateRow", b =>
                {
                    b.Property<string>("ProjectId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Stage")
                        .HasColumnType("TEXT");

                    b.Property<string>("TagsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("ProjectId", "Key");

                    b.HasIndex("ProjectId", "UpdatedAt");

                    b.ToTable("ProjectPromptTemplates", (string)null);
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Workflow.BacklogStateRow", b =>
                {
                    b.Property<string>("ProjectId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProjectId");

                    b.ToTable("BacklogStates");
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Workflow.IssueWorkflowProfile", b =>
                {
                    b.Property<string>("IssueId")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Prompts")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{}");

                    b.Property<string>("SourceTemplateId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Template")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Variables")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IssueId");

                    b.ToTable("IssueWorkflowProfiles", (string)null);
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Workflow.ProjectWorkflowProfile", b =>
                {
                    b.Property<string>("ProjectId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultTemplateId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Prompts")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{}");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Variables")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProjectId");

                    b.ToTable("ProjectWorkflowProfiles", (string)null);
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Workflow.ProjectWorkflowTemplateRow", b =>
                {
                    b.Property<string>("ProjectId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("TemplateId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Template")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("ProjectId", "TemplateId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectWorkflowTemplates", (string)null);
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Workflow.WorkflowLeaseRow", b =>
                {
                    b.Property<string>("WorkflowRunId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("WorkflowRunId");

                    b.ToTable("WorkflowLeases");
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Workflow.WorkflowRunRow", b =>
                {
                    b.Property<string>("WorkflowRunId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<long>("ETag")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MetadataProjectId")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasComputedColumnSql("json_extract(State, '$.Metadata.Annotations.projectId')", true);

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("WorkflowRunId");

                    b.HasIndex("MetadataProjectId");

                    b.ToTable("WorkflowRuns");
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Workflow.WorkflowStageLockRow", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("WorkflowStageLocks");
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Workflow.WorkflowVariablesRow", b =>
                {
                    b.Property<string>("WorkflowRunId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("WorkflowRunId");

                    b.ToTable("WorkflowVariables");
                });
#pragma warning restore 612, 618
        }
    }
}
