// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mohist.Server.Infrastructure.Data.Db;

#nullable disable

namespace Mohist.Server.Infrastructure.Data.Migrations
{
    [DbContext(typeof(MohistDbContext))]
    [Migration("20260629003200_AddInboxSubscriptionsTable")]
    partial class AddInboxSubscriptionsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Agent.AgentRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasComputedColumnSql("COALESCE(json_extract(State, '$.name'), json_extract(State, '$.Name'))", true);

                    b.Property<string>("ProjectId")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasComputedColumnSql("COALESCE(json_extract(State, '$.projectId'), json_extract(State, '$.ProjectId'))", true);

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasComputedColumnSql("COALESCE(json_extract(State, '$.status'), json_extract(State, '$.Status'))", true);

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Name")
                        .IsUnique();

                    b.HasIndex("ProjectId", "Status");

                    b.ToTable("Agents", (string)null);
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Epic.EpicCounterRow", b =>
                {
                    b.Property<string>("ProjectId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("Next")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProjectId");

                    b.ToTable("EpicCounters");
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Epic.EpicActiveIssueRow", b =>
                {
                    b.Property<string>("ProjectId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("IssueId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EpicId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("IssueNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProjectId", "IssueId");

                    b.HasIndex("ProjectId", "EpicId");

                    b.ToTable("EpicActiveIssues");
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Epic.EpicIssueRow", b =>
                {
                    b.Property<string>("EpicId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("IssueId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("IssueNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("EpicId", "IssueId");

                    b.HasIndex("ProjectId", "IssueId");

                    b.HasIndex("ProjectId", "IssueNumber");

                    b.ToTable("EpicIssues");
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Epic.EpicRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PauseReason")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Number");

                    b.HasIndex("ProjectId", "Status", "CreatedAt");

                    b.ToTable("Epics");
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Events.IssueEventRow", b =>
                {
                    b.Property<string>("Source")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("JSON");

                    b.Property<string>("DataContentType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtensionsJson")
                        .IsRequired()
                        .HasColumnType("JSON");

                    b.Property<string>("SpecVersion")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Source", "Id");

                    b.HasIndex("Type", "Source", "Id");

                    b.ToTable("IssueEvents", (string)null);
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Events.WorkflowRunEventRow", b =>
                {
                    b.Property<string>("Source")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("JSON");

                    b.Property<string>("DataContentType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtensionsJson")
                        .IsRequired()
                        .HasColumnType("JSON");

                    b.Property<string>("SpecVersion")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Source", "Id");

                    b.HasIndex("Type", "Source", "Id");

                    b.ToTable("WorkflowRunEvents", (string)null);
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Issue.AttachmentRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerKind")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_Attachments_ExpiresAt");

                    b.HasIndex("ProjectId", "OwnerKind", "OwnerId")
                        .HasDatabaseName("IX_Attachments_ProjectId_Owner");

                    b.ToTable("Attachments", (string)null);
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Issue.IssueCommentRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("IssueId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("IssueNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "IssueNumber", "CreatedAt");

                    b.ToTable("IssueComments");
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Issue.IssueCounterRow", b =>
                {
                    b.Property<string>("ProjectId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("Next")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProjectId");

                    b.ToTable("IssueCounters");
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Issue.IssuePrerequisiteRow", b =>
                {
                    b.Property<string>("ProjectId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("IssueNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrerequisiteNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("ProjectId", "IssueNumber", "PrerequisiteNumber");

                    b.ToTable("IssuePrerequisites");
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Issue.IssueRow", b =>
                {
                    b.Property<string>("IssueId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsArchived")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("INTEGER")
                        .HasComputedColumnSql("json_extract(State, '$.archivedAt') IS NOT NULL");

                    b.Property<bool?>("IsDraft")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("INTEGER")
                        .HasComputedColumnSql("COALESCE(json_extract(State, '$.isDraft'), json_extract(State, '$.IsDraft'))");

                    b.Property<int?>("Number")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("INTEGER")
                        .HasComputedColumnSql("COALESCE(json_extract(State, '$.number'), json_extract(State, '$.Number'))", true);

                    b.Property<string>("PrerequisiteNumbersJson")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasComputedColumnSql("COALESCE(json_extract(State, '$.prerequisiteNumbers'), json_extract(State, '$.PrerequisiteNumbers'))");

                    b.Property<string>("Priority")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasComputedColumnSql("COALESCE(json_extract(State, '$.priority'), json_extract(State, '$.Priority'))");

                    b.Property<string>("ProjectId")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasComputedColumnSql("COALESCE(json_extract(State, '$.projectId'), json_extract(State, '$.ProjectId'))", true);

                    b.Property<string>("Risk")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasComputedColumnSql("COALESCE(json_extract(State, '$.status'), json_extract(State, '$.Status'))");

                    b.Property<string>("Title")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasComputedColumnSql("COALESCE(json_extract(State, '$.title'), json_extract(State, '$.Title'))");

                    b.Property<string>("WorkflowRunId")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasComputedColumnSql("COALESCE(json_extract(State, '$.workflowRunId'), json_extract(State, '$.WorkflowRunId'))", true);

                    b.HasKey("IssueId");

                    b.HasIndex("Status");

                    b.HasIndex("WorkflowRunId");

                    b.HasIndex("ProjectId", "Number")
                        .IsUnique();

                    b.ToTable("Issues", (string)null);
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Issue.ProjectIssueTemplateRow", b =>
                {
                    b.Property<string>("ProjectId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Template")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("ProjectId", "Name");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectIssueTemplates", (string)null);
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Inbox.InboxItemRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("IssueId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("IssueNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IssueTitle")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("NotificationKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceEventId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceEventSource")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceEventSource", "SourceEventId")
                        .IsUnique()
                        .HasDatabaseName("UQ_InboxItems_SourceEvent");

                    b.HasIndex("ProjectId", "Id")
                        .HasDatabaseName("IX_InboxItems_ProjectId_Id");

                    b.HasIndex("ProjectId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_InboxItems_ProjectId_CreatedAt");

                    b.ToTable("InboxItems", null, t =>
                        {
                            t.HasCheckConstraint("CK_InboxItems_NotificationKind", "\"NotificationKind\" IN ('workflow_failed', 'approval_requested', 'issue_started', 'issue_completed')");
                        });
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Inbox.InboxSubscriptionRow", b =>
                {
                    b.Property<string>("ProjectId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ApprovalRequestedEnabled")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IssueCompletedEnabled")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IssueStartedEnabled")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("WorkflowFailedEnabled")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.HasKey("ProjectId");

                    b.ToTable("InboxSubscriptions", (string)null);
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Label.LabelDefinitionRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("SupportedValuesJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Key")
                        .IsUnique();

                    b.ToTable("LabelDefinitions", (string)null);
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Project.ProjectRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("TEXT");

                    b.Property<string>("RepositoriesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Runner.RunnerRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Slots")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Runners", null, t =>
                        {
                            t.HasCheckConstraint("CK_Runners_Slots_Positive", "\"Slots\" > 0");
                        });
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Runner.RunnerWorkRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("RunnerId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("TakenAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RunnerId", "Status");

                    b.HasIndex("RunnerId", "OwnerKind", "OwnerId", "WorkId");

                    b.ToTable("RunnerWorks", (string)null);
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Sessions.AgentSessionRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentSessionId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LabelIssueNumber")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasComputedColumnSql("json_extract(\"State\", '$.metadata.labels.\"mohist.io/issue-number\"')", true);

                    b.Property<string>("LabelProjectId")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasComputedColumnSql("json_extract(\"State\", '$.metadata.labels.\"mohist.io/project-id\"')", true);

                    b.Property<string>("LabelSessionName")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasComputedColumnSql("json_extract(\"State\", '$.metadata.labels.\"mohist.io/session-name\"')", true);

                    b.Property<string>("LabelSourceId")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasComputedColumnSql("json_extract(\"State\", '$.metadata.labels.\"mohist.io/source-id\"')", true);

                    b.Property<string>("LabelSourceKind")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasComputedColumnSql("json_extract(\"State\", '$.metadata.labels.\"mohist.io/source-kind\"')", true);

                    b.Property<string>("LabelStage")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasComputedColumnSql("json_extract(\"State\", '$.metadata.labels.\"mohist.io/stage\"')", true);

                    b.Property<string>("LabelWorkId")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasComputedColumnSql("json_extract(\"State\", '$.metadata.labels.\"mohist.io/work-id\"')", true);

                    b.Property<string>("LabelWorkType")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasComputedColumnSql("json_extract(\"State\", '$.metadata.labels.\"mohist.io/work-type\"')", true);

                    b.Property<DateTime?>("LastDataAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RunnerId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgentSessionId");

                    b.HasIndex("LabelSourceId")
                        .HasDatabaseName("IX_AgentSessions_LabelSourceId");

                    b.HasIndex("LabelProjectId", "CreatedAt")
                        .HasDatabaseName("IX_AgentSessions_LabelProjectId_CreatedAt");

                    b.HasIndex("LabelSourceId", "LabelSessionName")
                        .HasDatabaseName("IX_AgentSessions_LabelSourceId_LabelSessionName");

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("AgentSessions", (string)null);
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Sessions.AgentSessionTranscriptPartRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RawEventCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("TurnId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TurnId", "Sequence")
                        .IsUnique();

                    b.HasIndex("TurnId", "Type", "CorrelationKey")
                        .IsUnique();

                    b.ToTable("AgentSessionTranscriptParts", (string)null);
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Sessions.AgentSessionTranscriptTurnRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PromptKind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PromptText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "Sequence")
                        .IsUnique();

                    b.ToTable("AgentSessionTranscriptTurns", (string)null);
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Workflow.IssueWorkflowProfile", b =>
                {
                    b.Property<string>("IssueId")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Prompts")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{}");

                    b.Property<string>("SourceTemplateId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Template")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Variables")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IssueId");

                    b.ToTable("IssueWorkflowProfiles", (string)null);
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Workflow.ProjectWorkflowProfile", b =>
                {
                    b.Property<string>("ProjectId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultTemplateId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("DisableDefaultIssueTemplate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Prompts")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{}");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Variables")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProjectId");

                    b.ToTable("ProjectWorkflowProfiles", (string)null);
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Workflow.ProjectWorkflowTemplateRow", b =>
                {
                    b.Property<string>("ProjectId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("TemplateId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Template")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("ProjectId", "TemplateId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectWorkflowTemplates", (string)null);
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Workflow.Prompts.ProjectPromptTemplateRow", b =>
                {
                    b.Property<string>("ProjectId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Stage")
                        .HasColumnType("TEXT");

                    b.Property<string>("TagsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("ProjectId", "Key");

                    b.HasIndex("ProjectId", "UpdatedAt");

                    b.ToTable("ProjectPromptTemplates", (string)null);
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Workflow.WorkflowArtifactPendingUploadRow", b =>
                {
                    b.Property<string>("UploadId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FileCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("file");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<long?>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskRunId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkflowRunId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("UploadId");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_WorkflowArtifactPendingUploads_ExpiresAt");

                    b.HasIndex("WorkflowRunId", "WorkId", "TaskRunId", "Path")
                        .IsUnique()
                        .HasDatabaseName("UX_WorkflowArtifactPendingUploads_IdempotencyKey");

                    b.ToTable("WorkflowArtifactPendingUploads", (string)null);
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Workflow.WorkflowArtifactRow", b =>
                {
                    b.Property<string>("ArtifactId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ArtifactStoragePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("IssueId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("file");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TaskRunId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkflowRunId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("ArtifactId");

                    b.HasIndex("IssueId", "RecordedAt")
                        .HasDatabaseName("IX_WorkflowArtifacts_IssueId_RecordedAt");

                    b.HasIndex("WorkflowRunId", "Path", "RecordedAt")
                        .HasDatabaseName("IX_WorkflowArtifacts_WorkflowRunId_Path_RecordedAt");

                    b.HasIndex("WorkflowRunId", "TaskRunId", "RecordedAt")
                        .HasDatabaseName("IX_WorkflowArtifacts_WorkflowRunId_TaskRunId_RecordedAt");

                    b.ToTable("WorkflowArtifacts", (string)null);
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Workflow.WorkflowRunProfileRow", b =>
                {
                    b.Property<string>("WorkflowRunId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Variables")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("WorkflowRunId");

                    b.ToTable("WorkflowRunProfiles", (string)null);
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Workflow.WorkflowRunRow", b =>
                {
                    b.Property<string>("WorkflowRunId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedRunnerId")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasComputedColumnSql("COALESCE(json_extract(State, '$.assignment.runnerId'), json_extract(State, '$.claim.runnerId'))", false);

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasComputedColumnSql("json_extract(State, '$.metadata.createdAt')", false);

                    b.Property<long>("ETag")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MetadataProjectId")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasComputedColumnSql("COALESCE(json_extract(State, '$.metadata.annotations.projectId'), json_extract(State, '$.Metadata.Annotations.projectId'), json_extract(State, '$.Metadata.Annotations.ProjectId'))", true);

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("WorkflowRunId");

                    b.HasIndex("AssignedRunnerId");

                    b.HasIndex("MetadataProjectId");

                    b.HasIndex("MetadataProjectId", "AssignedRunnerId", "CreatedAt");

                    b.ToTable("WorkflowRuns");
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Workflow.WorkflowStageLockRow", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("WorkflowStageLocks");
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Workflow.WorkflowVariablesRow", b =>
                {
                    b.Property<string>("WorkflowRunId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("WorkflowRunId");

                    b.ToTable("WorkflowVariables");
                });
#pragma warning restore 612, 618
        }
    }
}
