// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore;
using Mohist.Server.Infrastructure.Data.Db;

#nullable disable

namespace Mohist.Server.Infrastructure.Data.Migrations;

[DbContext(typeof(MohistDbContext))]
[Migration("20260731100000_AddSlackDmSessionMapping")]
partial class AddSlackDmSessionMapping
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder) => MohistDbContextModelSnapshot.BuildModelCore(modelBuilder);
}