// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mohist.Server.Infrastructure.Data.Db;

#nullable disable

namespace Mohist.Server.Infrastructure.Data.Migrations
{
    [DbContext(typeof(MohistDbContext))]
    partial class MohistDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder) => BuildModelCore(modelBuilder);

        internal static void BuildModelCore(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Agent.AgentRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasComputedColumnSql("COALESCE(json_extract(State, '$.name'), json_extract(State, '$.Name'))", true);

                    b.Property<string>("ProjectId")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasComputedColumnSql("COALESCE(json_extract(State, '$.projectId'), json_extract(State, '$.ProjectId'))", true);

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasComputedColumnSql("COALESCE(json_extract(State, '$.status'), json_extract(State, '$.Status'))", true);

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Name")
                        .IsUnique();

                    b.HasIndex("ProjectId", "Status");

                    b.ToTable("Agents", (string)null);
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Agent.RoutingRuleRow", b =>
                {
                    b.Property<string>("Id").HasMaxLength(256).HasColumnType("TEXT");
                    b.Property<string>("ProjectId").IsRequired().HasMaxLength(256).HasColumnType("TEXT");
                    b.Property<string>("Name").IsRequired().HasMaxLength(256).HasColumnType("TEXT");
                    b.Property<int>("Position").HasColumnType("INTEGER");
                    b.Property<string>("Match").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("AgentId").IsRequired().HasMaxLength(256).HasColumnType("TEXT");
                    b.Property<string>("ResponsePrompt").IsRequired().HasColumnType("TEXT");
                    b.Property<bool>("Continue").HasColumnType("INTEGER");
                    b.Property<string>("Status").IsRequired().HasMaxLength(32).HasColumnType("TEXT");
                    b.Property<DateTimeOffset>("CreatedAt").HasColumnType("TEXT");
                    b.Property<DateTimeOffset>("UpdatedAt").HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("ProjectId").HasDatabaseName("IX_RoutingRules_ProjectId");
                    b.HasIndex("ProjectId", "Position").HasDatabaseName("IX_RoutingRules_ProjectId_Position");
                    b.HasIndex("ProjectId", "Name").IsUnique().HasDatabaseName("UX_RoutingRules_ProjectId_Name");
                    b.ToTable("RoutingRules", (string)null);
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Epic.EpicCounterRow", b =>
                {
                    b.Property<string>("ProjectId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("Next")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProjectId");

                    b.ToTable("EpicCounters");
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Epic.EpicRow", b =>
                {
                    b.Property<string>("ProjectId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PauseReason")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("ProjectId", "Number");

                    b.HasIndex("ProjectId", "Number")
                        .IsUnique();

                    b.HasIndex("ProjectId", "Status", "CreatedAt");

                    b.ToTable("Epics");
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Events.AgentSessionEventRow", b =>
                {
                    b.Property<string>("Source")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("JSON");

                    b.Property<string>("DataContentType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("DataStatus")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasComputedColumnSql("LOWER(COALESCE(json_extract(\"Data\", '$.status'), json_extract(\"Data\", '$.Status')))", true);

                    b.Property<DateTimeOffset?>("DispatchedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtensionsJson")
                        .IsRequired()
                        .HasColumnType("JSON");

                    b.Property<string>("SpecVersion")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeSortKey")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasComputedColumnSql("strftime('%Y-%m-%dT%H:%M:%S', \"Time\") ||\nsubstr(\n    CASE\n        WHEN instr(substr(\"Time\", 20), '+') > 0 THEN substr(\"Time\", 20, instr(substr(\"Time\", 20), '+') - 1)\n        WHEN instr(substr(\"Time\", 20), '-') > 0 THEN substr(\"Time\", 20, instr(substr(\"Time\", 20), '-') - 1)\n        ELSE ''\n    END || '.0000000',\n    1,\n    8\n) || 'Z'", true);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Source", "Id");

                    b.HasIndex("Source", "Id")
                        .HasDatabaseName("IX_AgentSessionEvents_Undelivered")
                        .HasFilter("\"DispatchedAt\" IS NULL");

                    b.HasIndex("Type", "Time");

                    b.HasIndex("TimeSortKey", "Source", "Id")
                        .HasDatabaseName("IX_AgentSessionEvents_TimeSortKey_Source_Id");

                    b.HasIndex("Type", "Source", "Id");

                    b.HasIndex("DataStatus", "Type", "TimeSortKey", "Source", "Id")
                        .HasDatabaseName("IX_AgentSessionEvents_DataStatus_Type_TimeSortKey_Source_Id");

                    b.ToTable("AgentSessionEvents", (string)null);
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Events.DeadLetterRow", b =>
                {
                    b.Property<long>("DeadLetterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("JSON");

                    b.Property<string>("DataContentType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DeadLetteredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorStack")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtensionsJson")
                        .IsRequired()
                        .HasColumnType("JSON");

                    b.Property<string>("FailingHandler")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("RedeliveryAttemptedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("SpecVersion")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("DeadLetterId");

                    b.HasIndex("DeadLetteredAt");

                    b.HasIndex("FailingHandler", "DeadLetteredAt");

                    b.HasIndex("Source", "Id", "FailingHandler")
                        .IsUnique();

                    b.ToTable("DeadLetters", (string)null);
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Events.EpicEventRow", b =>
                {
                    b.Property<string>("Source")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("JSON");

                    b.Property<string>("DataContentType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DispatchedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtensionsJson")
                        .IsRequired()
                        .HasColumnType("JSON");

                    b.Property<string>("SpecVersion")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("TimelineSource")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasDefaultValue("")
                        .HasColumnType("TEXT");

                    b.HasKey("Source", "Id");

                    b.HasIndex("Source", "Id", "DispatchedAt")
                        .HasDatabaseName("IX_EpicEvents_Source_Id_DispatchedAt")
                        .HasFilter("\"DispatchedAt\" IS NULL");

                    b.HasIndex("TimelineSource", "Time", "Source", "Id")
                        .HasDatabaseName("IX_EpicEvents_TimelineSource_Time_Source_Id");

                    b.HasIndex("Type", "Source", "Id");

                    b.ToTable("EpicEvents", (string)null);
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Events.IssueEventRow", b =>
                {
                    b.Property<string>("Source")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("JSON");

                    b.Property<string>("DataContentType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DispatchedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtensionsJson")
                        .IsRequired()
                        .HasColumnType("JSON");

                    b.Property<string>("SpecVersion")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeSortKey")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasComputedColumnSql("strftime('%Y-%m-%dT%H:%M:%S', \"Time\") ||\nsubstr(\n    CASE\n        WHEN instr(substr(\"Time\", 20), '+') > 0 THEN substr(\"Time\", 20, instr(substr(\"Time\", 20), '+') - 1)\n        WHEN instr(substr(\"Time\", 20), '-') > 0 THEN substr(\"Time\", 20, instr(substr(\"Time\", 20), '-') - 1)\n        ELSE ''\n    END || '.0000000',\n    1,\n    8\n) || 'Z'", true);

                    b.Property<string>("TimelineSource")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasDefaultValue("")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Source", "Id");

                    b.HasIndex("Source", "Id", "DispatchedAt")
                        .HasDatabaseName("IX_IssueEvents_Source_Id_DispatchedAt")
                        .HasFilter("\"DispatchedAt\" IS NULL");

                    b.HasIndex("TimeSortKey", "Source", "Id")
                        .HasDatabaseName("IX_IssueEvents_TimeSortKey_Source_Id");

                    b.HasIndex("TimelineSource", "Time", "Source", "Id")
                        .HasDatabaseName("IX_IssueEvents_TimelineSource_Time_Source_Id");

                    b.HasIndex("Type", "Source", "Id");

                    b.ToTable("IssueEvents", (string)null);
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Events.WorkflowRunEventRow", b =>
                {
                    b.Property<string>("Source")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("JSON");

                    b.Property<string>("DataContentType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DispatchedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtensionsJson")
                        .IsRequired()
                        .HasColumnType("JSON");

                    b.Property<string>("SpecVersion")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeSortKey")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasComputedColumnSql("strftime('%Y-%m-%dT%H:%M:%S', \"Time\") ||\nsubstr(\n    CASE\n        WHEN instr(substr(\"Time\", 20), '+') > 0 THEN substr(\"Time\", 20, instr(substr(\"Time\", 20), '+') - 1)\n        WHEN instr(substr(\"Time\", 20), '-') > 0 THEN substr(\"Time\", 20, instr(substr(\"Time\", 20), '-') - 1)\n        ELSE ''\n    END || '.0000000',\n    1,\n    8\n) || 'Z'", true);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Source", "Id");

                    b.HasIndex("Source", "Id", "DispatchedAt")
                        .HasDatabaseName("IX_WorkflowRunEvents_Source_Id_DispatchedAt")
                        .HasFilter("\"DispatchedAt\" IS NULL");

                    b.HasIndex("TimeSortKey", "Source", "Id")
                        .HasDatabaseName("IX_WorkflowRunEvents_TimeSortKey_Source_Id");

                    b.HasIndex("Type", "Source", "Id");

                    b.ToTable("WorkflowRunEvents", (string)null);
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Inbox.InboxItemRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("IssueNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IssueTitle")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("NotificationKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceEventId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceEventSource")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_InboxItems_ProjectId_CreatedAt");

                    b.HasIndex("ProjectId", "Id")
                        .HasDatabaseName("IX_InboxItems_ProjectId_Id");

                    b.HasIndex("SourceEventSource", "SourceEventId")
                        .IsUnique()
                        .HasDatabaseName("UQ_InboxItems_SourceEvent");

                    b.ToTable("InboxItems", null, t =>
                        {
                            t.HasCheckConstraint("CK_InboxItems_NotificationKind", "\"NotificationKind\" IN ('workflow_failed', 'approval_requested', 'issue_started', 'issue_completed')");
                        });
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Inbox.InboxSubscriptionRow", b =>
                {
                    b.Property<string>("ProjectId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ApprovalRequestedEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IssueCompletedEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IssueStartedEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("WorkflowFailedEnabled")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProjectId");

                    b.ToTable("InboxSubscriptions", (string)null);
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Issue.AttachmentRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int?>("OwnerIssueNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OwnerKind")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_Attachments_ExpiresAt");

                    b.HasIndex("ProjectId", "OwnerKind", "OwnerId")
                        .HasDatabaseName("IX_Attachments_ProjectId_Owner");

                    b.HasIndex("ProjectId", "OwnerKind", "OwnerIssueNumber")
                        .HasDatabaseName("IX_Attachments_ProjectId_OwnerIssueNumber");

                    b.ToTable("Attachments", (string)null);
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Issue.IssueCommentRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("IssueNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "IssueNumber", "CreatedAt");

                    b.ToTable("IssueComments");
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Issue.IssueCounterRow", b =>
                {
                    b.Property<string>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Next")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProjectId");

                    b.ToTable("IssueCounters");
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Issue.IssuePrerequisiteRow", b =>
                {
                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("IssueNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrerequisiteNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("ProjectId", "IssueNumber", "PrerequisiteNumber");

                    b.ToTable("IssuePrerequisites");
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Issue.IssueRow", b =>
                {
                    b.Property<string>("ProjectId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EpicNumber")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsArchived")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("INTEGER")
                        .HasComputedColumnSql("json_extract(State, '$.archivedAt') IS NOT NULL");

                    b.Property<bool?>("IsDraft")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("INTEGER")
                        .HasComputedColumnSql("COALESCE(json_extract(State, '$.isDraft'), json_extract(State, '$.IsDraft'))");

                    b.Property<int?>("ParentIssueNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrerequisiteNumbersJson")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasComputedColumnSql("COALESCE(json_extract(State, '$.prerequisiteNumbers'), json_extract(State, '$.PrerequisiteNumbers'))");

                    b.Property<string>("Priority")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasComputedColumnSql("COALESCE(json_extract(State, '$.priority'), json_extract(State, '$.Priority'))");

                    b.Property<string>("RepositoryName")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasComputedColumnSql("COALESCE(json_extract(State, '$.repositoryRef'), json_extract(State, '$.RepositoryRef'))", true);

                    b.Property<string>("Risk")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasComputedColumnSql("COALESCE(json_extract(State, '$.status'), json_extract(State, '$.Status'))");

                    b.Property<string>("Title")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasComputedColumnSql("COALESCE(json_extract(State, '$.title'), json_extract(State, '$.Title'))");

                    b.Property<string>("WorkflowRunId")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasComputedColumnSql("COALESCE(json_extract(State, '$.workflowRunId'), json_extract(State, '$.WorkflowRunId'))", true);

                    b.HasKey("ProjectId", "Number");

                    b.HasIndex("Status");

                    b.HasIndex("WorkflowRunId");

                    b.HasIndex("ProjectId", "Number")
                        .IsUnique();

                    b.HasIndex("ProjectId", "EpicNumber", "Number");

                    b.HasIndex("ProjectId", "ParentIssueNumber", "Number");

                    b.HasIndex("ProjectId", "RepositoryName", "Status")
                        .HasDatabaseName("IX_Issues_ProjectId_RepositoryName_Status");

                    b.ToTable("Issues", (string)null);
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Issue.ProjectIssueTemplateRow", b =>
                {
                    b.Property<string>("ProjectId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Template")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("ProjectId", "Name");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectIssueTemplates", (string)null);
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Label.LabelDefinitionRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("SupportedValuesJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Key")
                        .IsUnique();

                    b.ToTable("LabelDefinitions", (string)null);
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Project.ProjectRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastRepositoryCommandJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("TEXT");

                    b.Property<string>("RepositoriesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("RepositoryRevision")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Runner.RunnerRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Slots")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Runners", null, t =>
                        {
                            t.HasCheckConstraint("CK_Runners_Slots_Positive", "\"Slots\" > 0");
                        });
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Runner.RunnerWorkRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("RunnerId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("TakenAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RunnerId", "Status");

                    b.HasIndex("RunnerId", "OwnerKind", "OwnerId", "WorkId");

                    b.ToTable("RunnerWorks", (string)null);
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Runner.TaskLogBatchRow", b =>
                {
                    b.Property<string>("OwnerKind")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Truncated")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("OwnerKind", "OwnerId", "WorkId");

                    b.ToTable("TaskLogBatches", (string)null);
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Runner.TaskLogEntryRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<long>("Seq")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerKind", "OwnerId", "WorkId", "Seq")
                        .IsUnique()
                        .HasDatabaseName("IX_TaskLogEntries_Owner_WorkId_Seq");

                    b.ToTable("TaskLogEntries", (string)null);
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Sessions.AgentSessionRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentSessionId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LabelAgentId")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasComputedColumnSql("json_extract(\"State\", '$.metadata.labels.\"mohist.io/agent-id\"')", true);

                    b.Property<string>("LabelAgentLaunchEpicNumber")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasComputedColumnSql("json_extract(\"State\", '$.metadata.labels.\"mohist.io/agent-launch/epic-number\"')", true);

                    b.Property<string>("LabelAgentLaunchIssueNumber")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasComputedColumnSql("json_extract(\"State\", '$.metadata.labels.\"mohist.io/agent-launch/issue-number\"')", true);

                    b.Property<string>("LabelAgentLaunchRepository")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasComputedColumnSql("json_extract(\"State\", '$.metadata.labels.\"mohist.io/agent-launch/repository\"')", true);

                    b.Property<string>("LabelAgentLaunchWorkspacePath")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasComputedColumnSql("json_extract(\"State\", '$.metadata.labels.\"mohist.io/agent-launch/workspace-path\"')", true);

                    b.Property<string>("LabelAgentName")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasComputedColumnSql("json_extract(\"State\", '$.metadata.labels.\"mohist.io/agent-name\"')", true);

                    b.Property<string>("LabelIssueNumber")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasComputedColumnSql("json_extract(\"State\", '$.metadata.labels.\"mohist.io/issue-number\"')", true);

                    b.Property<string>("LabelProjectId")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasComputedColumnSql("json_extract(\"State\", '$.metadata.labels.\"mohist.io/project-id\"')", true);

                    b.Property<string>("LabelSessionName")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasComputedColumnSql("json_extract(\"State\", '$.metadata.labels.\"mohist.io/session-name\"')", true);

                    b.Property<string>("LabelSourceId")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasComputedColumnSql("json_extract(\"State\", '$.metadata.labels.\"mohist.io/source-id\"')", true);

                    b.Property<string>("LabelSourceKind")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasComputedColumnSql("json_extract(\"State\", '$.metadata.labels.\"mohist.io/source-kind\"')", true);

                    b.Property<string>("LabelStage")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasComputedColumnSql("json_extract(\"State\", '$.metadata.labels.\"mohist.io/stage\"')", true);

                    b.Property<string>("LabelTriggerEventId")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasComputedColumnSql("json_extract(\"State\", '$.metadata.labels.\"mohist.io/trigger/event-id\"')", false);

                    b.Property<string>("LabelTriggerRuleId")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasComputedColumnSql("json_extract(\"State\", '$.metadata.labels.\"mohist.io/trigger/rule-id\"')", false);

                    b.Property<string>("LabelWorkId")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasComputedColumnSql("json_extract(\"State\", '$.metadata.labels.\"mohist.io/work-id\"')", true);

                    b.Property<string>("LabelWorkType")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasComputedColumnSql("json_extract(\"State\", '$.metadata.labels.\"mohist.io/work-type\"')", true);

                    b.Property<DateTime?>("LastDataAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RunnerId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgentSessionId");

                    b.HasIndex("LabelAgentLaunchEpicNumber")
                        .HasDatabaseName("IX_AgentSessions_LabelAgentLaunchEpicNumber");

                    b.HasIndex("LabelAgentLaunchIssueNumber")
                        .HasDatabaseName("IX_AgentSessions_LabelAgentLaunchIssueNumber");

                    b.HasIndex("LabelSourceId")
                        .HasDatabaseName("IX_AgentSessions_LabelSourceId");

                    b.HasIndex("LabelProjectId", "CreatedAt")
                        .HasDatabaseName("IX_AgentSessions_LabelProjectId_CreatedAt");

                    b.HasIndex("LabelSourceId", "LabelSessionName")
                        .HasDatabaseName("IX_AgentSessions_LabelSourceId_LabelSessionName");

                    b.HasIndex("Status", "CreatedAt");

                    b.HasIndex("LabelAgentId", "LabelProjectId", "CreatedAt")
                        .HasDatabaseName("IX_AgentSessions_LabelAgentId_LabelProjectId_CreatedAt");

                    b.HasIndex("LabelProjectId", "LabelAgentLaunchEpicNumber", "CreatedAt")
                        .HasDatabaseName("IX_AgentSessions_LabelProjectId_LabelAgentLaunchEpicNumber_CreatedAt");

                    b.HasIndex("LabelProjectId", "LabelAgentLaunchIssueNumber", "CreatedAt")
                        .HasDatabaseName("IX_AgentSessions_LabelProjectId_LabelAgentLaunchIssueNumber_CreatedAt");

                    b.HasIndex("LabelProjectId", "LabelIssueNumber", "CreatedAt")
                        .HasDatabaseName("IX_AgentSessions_LabelProjectId_LabelIssueNumber_CreatedAt");

                    b.ToTable("AgentSessions", (string)null);
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Sessions.AgentSessionTranscriptPartRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadStatus")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasComputedColumnSql("LOWER(COALESCE(json_extract(\"PayloadJson\", '$.status'), json_extract(\"PayloadJson\", '$.Status')))", true);

                    b.Property<int>("RawEventCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("TurnId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TurnId", "Sequence")
                        .IsUnique();

                    b.HasIndex("TurnId", "Type", "CorrelationKey")
                        .IsUnique();

                    b.HasIndex("Type", "PayloadStatus", "LastSeenAt", "Id")
                        .HasDatabaseName("IX_AgentSessionTranscriptParts_Type_PayloadStatus_LastSeenAt_Id");

                    b.ToTable("AgentSessionTranscriptParts", (string)null);
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Sessions.AgentSessionTranscriptTurnRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PromptKind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PromptText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RuntimeSessionId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "Sequence")
                        .IsUnique();

                    b.HasIndex("SessionId", "RuntimeSessionId", "Sequence");

                    b.ToTable("AgentSessionTranscriptTurns", (string)null);
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Workflow.IssueWorkflowProfile", b =>
                {
                    b.Property<string>("ProjectId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("IssueNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Prompts")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{}");

                    b.Property<string>("SourceTemplateId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Template")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Variables")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProjectId", "IssueNumber");

                    b.HasIndex("ProjectId", "IssueNumber")
                        .IsUnique();

                    b.ToTable("IssueWorkflowProfiles", (string)null);
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Workflow.ProjectWorkflowProfile", b =>
                {
                    b.Property<string>("ProjectId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultTemplateId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("DisableDefaultIssueTemplate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("DisabledWorkflowProfileIds")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<string>("Prompts")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{}");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Variables")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProjectId");

                    b.ToTable("ProjectWorkflowProfiles", (string)null);
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Workflow.ProjectWorkflowTemplateRow", b =>
                {
                    b.Property<string>("ProjectId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("TemplateId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Template")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("ProjectId", "TemplateId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectWorkflowTemplates", (string)null);
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Workflow.Prompts.ProjectPromptTemplateRow", b =>
                {
                    b.Property<string>("ProjectId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Stage")
                        .HasColumnType("TEXT");

                    b.Property<string>("TagsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("ProjectId", "Key");

                    b.HasIndex("ProjectId", "UpdatedAt");

                    b.ToTable("ProjectPromptTemplates", (string)null);
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Workflow.WorkflowArtifactPendingUploadRow", b =>
                {
                    b.Property<string>("UploadId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FileCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("file");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<long?>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskRunId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkflowRunId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("UploadId");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_WorkflowArtifactPendingUploads_ExpiresAt");

                    b.HasIndex("WorkflowRunId", "WorkId", "TaskRunId", "Path")
                        .IsUnique()
                        .HasDatabaseName("UX_WorkflowArtifactPendingUploads_IdempotencyKey");

                    b.ToTable("WorkflowArtifactPendingUploads", (string)null);
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Workflow.WorkflowArtifactRow", b =>
                {
                    b.Property<string>("ArtifactId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ArtifactStoragePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int?>("IssueNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("file");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TaskRunId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkflowRunId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("ArtifactId");

                    b.HasIndex("ProjectId", "IssueNumber", "RecordedAt")
                        .HasDatabaseName("IX_WorkflowArtifacts_ProjectId_IssueNumber_RecordedAt");

                    b.HasIndex("WorkflowRunId", "Path", "RecordedAt")
                        .HasDatabaseName("IX_WorkflowArtifacts_WorkflowRunId_Path_RecordedAt");

                    b.HasIndex("WorkflowRunId", "TaskRunId", "RecordedAt")
                        .HasDatabaseName("IX_WorkflowArtifacts_WorkflowRunId_TaskRunId_RecordedAt");

                    b.ToTable("WorkflowArtifacts", (string)null);
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Workflow.WorkflowRunProfileRow", b =>
                {
                    b.Property<string>("WorkflowRunId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Variables")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("WorkflowRunId");

                    b.ToTable("WorkflowRunProfiles", (string)null);
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Workflow.WorkflowRunRow", b =>
                {
                    b.Property<string>("WorkflowRunId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedWorkerId")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasComputedColumnSql("COALESCE(json_extract(State, '$.assignment.workerId'), json_extract(State, '$.assignment.runnerId'), json_extract(State, '$.claim.runnerId'))", false);

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasComputedColumnSql("json_extract(State, '$.metadata.createdAt')", false);

                    b.Property<long>("ETag")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EpicNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IssueNumber")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("INTEGER")
                        .HasComputedColumnSql("CAST(COALESCE(json_extract(State, '$.metadata.annotations.issueNumber'), json_extract(State, '$.Metadata.Annotations.issueNumber'), json_extract(State, '$.Metadata.Annotations.IssueNumber')) AS INTEGER)", true);

                    b.Property<string>("MetadataProjectId")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasComputedColumnSql("COALESCE(json_extract(State, '$.metadata.annotations.projectId'), json_extract(State, '$.Metadata.Annotations.projectId'), json_extract(State, '$.Metadata.Annotations.ProjectId'))", true);

                    b.Property<DateTime?>("ReadySince")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasComputedColumnSql("COALESCE(json_extract(State, '$.readySince'), json_extract(State, '$.ReadySince'))", false);

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasComputedColumnSql("LOWER(COALESCE(json_extract(State, '$.status'), json_extract(State, '$.Status')))", true);

                    b.HasKey("WorkflowRunId");

                    b.HasIndex("AssignedWorkerId");

                    b.HasIndex("MetadataProjectId");

                    b.HasIndex("MetadataProjectId", "EpicNumber")
                        .HasDatabaseName("IX_WorkflowRuns_ProjectId_EpicNumber");

                    b.HasIndex("MetadataProjectId", "IssueNumber")
                        .HasDatabaseName("IX_WorkflowRuns_ProjectId_IssueNumber");

                    b.HasIndex("Status", "AssignedWorkerId")
                        .HasDatabaseName("IX_WorkflowRuns_Status");

                    b.HasIndex("MetadataProjectId", "AssignedWorkerId", "CreatedAt");

                    b.HasIndex("Status", "AssignedWorkerId", "ReadySince")
                        .HasDatabaseName("IX_WorkflowRuns_Status_ReadySince");

                    b.ToTable("WorkflowRuns");
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Workflow.WorkflowStageLockRow", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("WorkflowStageLocks");
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Workflow.WorkflowVariablesRow", b =>
                {
                    b.Property<string>("WorkflowRunId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("WorkflowRunId");

                    b.ToTable("WorkflowVariables");
                });

            modelBuilder.Entity("Mohist.Server.Infrastructure.Data.Inbox.InboxSubscriptionRow", b =>
                {
                    b.HasOne("Mohist.Server.Infrastructure.Data.Project.ProjectRow", null)
                        .WithOne()
                        .HasForeignKey("Mohist.Server.Infrastructure.Data.Inbox.InboxSubscriptionRow", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
