import * as fs from 'node:fs';
import * as path from 'node:path';

export type SkillResult = 'created' | 'updated' | 'unchanged' | 'skipped-protected' | 'overwritten';

export interface SkillOperationResult {
  skill: string;
  result: SkillResult;
  reason?: string;
}

const MOHIST_MARKER = '<!-- Generated by Mohist -->';
const CHECKSUM_HEADER = '<!-- checksum: ';

function computeChecksum(content: string): string {
  const crypto = require('node:crypto');
  return crypto.createHash('sha256').update(content).digest('hex').slice(0, 16);
}

function parseFrontmatter(content: string): { name: string; description: string; body: string } | null {
  const match = content.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!match) return null;

  const frontmatterStr = match[1];
  const body = match[2];

  const nameMatch = frontmatterStr.match(/^name:\s*(.+)$/m);
  const descMatch = frontmatterStr.match(/^description:\s*(.+)$/m);

  if (!nameMatch || !descMatch) return null;

  return {
    name: nameMatch[1].trim(),
    description: descMatch[1].trim(),
    body,
  };
}

function extractContentWithoutMarker(content: string): string {
  const markerIdx = content.indexOf(MOHIST_MARKER);
  if (markerIdx === -1) return content;

  const afterMarker = content.slice(markerIdx + MOHIST_MARKER.length).trim();
  const checksumStart = afterMarker.indexOf(CHECKSUM_HEADER);
  if (checksumStart === -1) return afterMarker;

  const checksumEnd = afterMarker.indexOf(' -->', checksumStart);
  if (checksumEnd === -1) return afterMarker;

  return afterMarker.slice(checksumEnd + 4).trim();
}

function isGeneratedFile(content: string): boolean {
  return content.includes(MOHIST_MARKER) && content.includes(CHECKSUM_HEADER);
}

function isMohistGenerated(content: string): boolean {
  if (!isGeneratedFile(content)) return false;

  const withoutMarker = extractContentWithoutMarker(content);
  const checksumMatch = content.match(/checksum: ([a-f0-9]+)/);
  if (!checksumMatch) return false;

  const expectedChecksum = computeChecksum(withoutMarker);
  return checksumMatch[1] === expectedChecksum;
}

const MOHIST_TEMPLATE = `---
name: mohist
description: 执行 mohist CLI 操作。当用户要求创建、查看、启动、审批、关闭 issue，查看项目状态或日志，或任何涉及 "mo" 命令的操作时使用。触发词包括 "create issue"、"创建 issue"、"list issues"、"start issue"、"approve"、"reject"、"mo issue"、"mo status"、"查看 issue"、"issue 日志"。
---

# mohist CLI

mohist 命令前缀为 \`mo\`。操作前确认 server 在运行：\`mo server status\`

## Issue 命令

\`\`\`
mo issue create <title> --body <text> --label <label> --priority <P0|P1|P2>
mo issue list [-s <stage>] [-l <label>] [-p <priority>] [--all] [--archived]
mo issue show <number>
mo issue start <number>
mo issue approve <number>
mo issue reject <number> -m <reason>
mo issue close <number>
mo issue reopen <number>
mo issue comment <number> <text>
mo issue logs <number> [-f]
mo issue diff <number>
mo issue update <number> --title <text> --body <text> --label <+add|-remove>
mo issue archive <number>
mo issue archive --all-completed
mo issue unarchive <number>
\`\`\`

## 其他命令

\`\`\`
mo status                          当前项目概览
mo project list / use <name>       项目管理
mo attach [-f]                     实时跟踪 agent 事件（交互式 REPL）
mo server start / stop / status    服务管理
mo server update                   重新构建并重启（源码模式）
\`\`\`

## 常用模式

创建并启动：
\`\`\`bash
mo issue create "Fix X" --body "描述" --label bug --priority P1
mo issue start <number>
\`\`\`

监控进度：
\`\`\`bash
mo issue show <number>     # 查看状态
mo issue logs <number> -f  # 实时日志
mo attach -f               # 全局事件流
\`\`\`

审批或拒绝：
\`\`\`bash
mo issue approve <number>
mo issue reject <number> -m "原因"
\`\`\`

审查变更：
\`\`\`bash
mo issue diff <number>     # 查看代码差异
\`\`\`

## 注意

- \`mo issue start\` 会启动 agent 自动处理，需要 server 运行
- \`mo attach\` 是交互式 REPL，用于审批和回答 agent 问题
- \`logs -f\` 跟踪实时输出，不带 \`-f\` 看历史
- \`diff\` 在 issue 进入 Build 阶段后才有内容`;

const MOHIST_EXPLORE_TEMPLATE = `---
name: mohist-explore
description: 从产品和用户视角探索 mohist 项目，发现功能缺陷、体验问题、设计机会和价值增长点。当用户想要探索代码库、发现改进点、审查用户体验、思考功能设计、或无目标地巡检产品时使用。触发词包括 "explore"、"探索"、"巡检"、"找问题"、"体验审查"、"功能设计"、"产品思考"。
---

Enter explore mode. Think deeply. Visualize freely. Follow the conversation wherever it goes.

**IMPORTANT: Explore mode is for thinking, not implementing.** You may read files, search code, and investigate the codebase, but you must NEVER write code or implement features. If you may offer to create mohist issues to capture findings—that's capturing thinking, not implementing.

**This is a stance, not a workflow.** There are no fixed steps, no required sequence, no mandatory outputs. You're a thinking partner helping the user explore.

---

## The Stance

- **User-first** — 每个发现都过一道：用户会怎么感知？用产品语言描述问题，不用实现细节。这不是"代码有什么 bug"，而是"用户在哪会卡住"。
- **Value-oriented** — 区分"能跑"和"好用"。追问：这个功能交付的核心价值是什么？用户真的需要这个吗？什么让用户觉得值？
- **Journey-aware** — 想象用户的完整操作路径。用户从哪来？要到哪去？中间会困惑吗？会惊喜吗？摩擦在哪？
- **Curious, not prescriptive** — Ask questions that emerge naturally, don't follow a script
- **Open threads, not interrogations** — Surface multiple interesting directions and let the user follow what resonates
- **Visual** — Use ASCII diagrams liberally when they'd help clarify thinking
- **Grounded** — Explore the actual codebase when relevant, don't just theorize

---

## What You Might Do

Depending on what the user brings, you might:

**Explore the product from a user's perspective**
- Walk through user journeys end to end
- Identify friction points and moments of confusion
- Find missing feedback, broken flows, dead ends
- Ask: "If I were a user, would I understand what's happening?"

**Investigate the codebase**
- Map architecture relevant to the discussion
- Find integration points and hidden complexity
- Understand how features are actually implemented vs. how they appear to users

**Think through feature design**
- Explore what "complete" looks like for a feature
- Consider edge cases from the user's angle
- Compare approaches with user value as the yardstick

**Visualize**
\`\`\`
┌─────────────────────────────────────────┐
│     Use ASCII diagrams liberally        │
├─────────────────────────────────────────┤
│                                         │
│   User Journey    Data Flow    System   │
│                                         │
│   ┌──────┐        ┌──────┐             │
│   │ Step │───────▶│ Step │             │
│   │   A  │        │   B  │             │
│   └──────┘        └──────┘             │
│                                         │
│   State machines, journey maps,         │
│   comparison tables, priority matrices  │
│                                         │
└─────────────────────────────────────────┘
\`\`\`

**Surface risks and unknowns**
- What could frustrate users?
- What assumptions might be wrong?
- What's the cost of not addressing something?

---

## Mohist Context

了解当前项目状态，快速切入：

\`\`\`bash
mo status
mo issue list
\`\`\`

项目结构参见根目录 \`AGENTS.md\`。

### 当用户提到已有 issue

如果用户提到 issue 编号或讨论中涉及已有 issue，先了解上下文：

\`\`\`bash
mo issue show <number>
\`\`\`

理解 issue 的当前状态、阶段、已有讨论，然后在此基础上深入。

### 当探索无特定目标

系统性巡检 mohist 产品。以下是探索维度（不必全部覆盖，根据直觉选择有趣的切入）：

**用户旅程完整性**
- 新用户 onboarding 路径顺畅吗？
- 核心流程（create → start → monitor → approve → done）每一步的体验如何？
- 审批点给用户的信息够吗？用户知道该审什么、怎么审吗？

**反馈与可感知性**
- 操作后有反馈吗？（loading、success、error）
- 异步任务（agent 运行）的进度可感知吗？
- 错误信息用户能理解吗？能据此采取行动吗？

**功能完备性**
- 已有功能做到了什么程度？离"好用"还差什么？
- 有没有功能做了 80% 但缺失关键的最后 20%？
- 边界情况处理了吗？优雅降级了吗？

**一致性与连贯性**
- CLI 和 Web UI 的概念一致吗？
- 命名、术语、交互模式统一吗？
- 不同页面/视图之间的导航流畅吗？

**技术债务的产品影响**
- 有没有技术问题在影响用户体验？
- 有没有"用户会感知到"的性能问题？
- 可观测性足够吗？出问题时用户能诊断吗？

---

## Handling Different Entry Points

**User brings no topic (free exploration):**
\`\`\`
User: (进入 explore mode，无特定主题)

You: 让我看看当前产品状态...

      [读取 mo status, mo issue list]

      当前 X 个活跃 issue，Y 个在 pipeline 中。
      有意思的是...

      [自然地开始讨论观察到的东西]
\`\`\`

**User brings a product concern:**
\`\`\`
User: review/approve 的体验不太好

You: [读代码 + 看 UI]

      用户在审批时需要什么？

      ┌──────────────────────────────────────────┐
      │          Review 用户旅程                  │
      ├──────────────────────────────────────────┤
      │                                          │
      │   看到需要审批  →  理解变更  →  做决定    │
      │        │              │           │       │
      │     通知够吗？    信息够吗？    选项对吗？  │
      │                                          │
      └──────────────────────────────────────────┘

      用户在每个节点会卡在哪？
\`\`\`

**User brings a feature to design:**
\`\`\`
User: 想想归档功能应该怎么做

You: 从用户角度，归档解决了什么问题？

      用户故事：我的 issue 列表越来越长，已完成的不需要
      天天看到，但我偶尔需要翻历史。

      那归档的核心价值是：清理视野，保留可查。

      完备的归档需要覆盖...
\`\`\`

**User brings a bug or problem:**
\`\`\`
User: 这个页面白屏了

You: [追踪问题]

      用户视角：我点了一个链接，页面白屏了，什么都没说。
      这比 bug 本身更严重的是——用户不知道发生了什么，
      也不确定该怎么办。

      根因是...但产品层面的修复不只是修代码...
\`\`\`

---

## Ending Discovery

There's no required ending. Discovery might:

- **Flow into an issue**: "This feels like a real pain point. Want me to create an issue?"
- **Result in multiple findings**: Surface a list of issues to create
- **Just provide clarity**: User has what they need, moves on
- **Continue later**: "We can pick this up anytime"

When things crystallize, you might summarize:

\`\`\`
## What We Found

**User pain points**: [from user's perspective]
**Quick wins**: [high value, low effort]
**Design decisions needed**: [if any]
**Open questions**: [if any remain]

**Next steps**:
- Create issues for findings
- Keep exploring: just keep talking
\`\`\`

But this summary is optional. Sometimes the thinking IS the value.

---

## Guardrails

- **Don't implement** — Never write code or implement features. Creating mohist issues is fine, writing application code is not.
- **Don't fake understanding** — If something is unclear, dig deeper
- **Don't rush** — Discovery is thinking time, not task time
- **Don't force structure** — Let patterns emerge naturally
- **Don't auto-capture** — Offer to create issues, don't just do it
- **Do visualize** — A good diagram is worth many paragraphs
- **Do explore the codebase** — Ground discussions in reality
- **Do think like a user** — Always come back to: what does the user experience?`;

const SHARED_SKILLS: Record<string, string> = {
  mohist: MOHIST_TEMPLATE,
  'mohist-explore': MOHIST_EXPLORE_TEMPLATE,
};

function buildMarkedContent(template: string): string {
  const checksum = computeChecksum(template);
  return `${MOHIST_MARKER}\n<!-- checksum: ${checksum} -->\n${template}`;
}

function ensureDir(dirPath: string): void {
  if (!fs.existsSync(dirPath)) {
    fs.mkdirSync(dirPath, { recursive: true });
  }
}

function writeSkillFile(skillPath: string, content: string): void {
  ensureDir(path.dirname(skillPath));
  fs.writeFileSync(skillPath, content, 'utf-8');
}

export interface InstallOptions {
  projectPath?: string;
  force?: boolean;
}

export interface UpdateOptions {
  projectPath?: string;
}

export function installSharedAgentSkills(options: InstallOptions = {}): SkillOperationResult[] {
  const basePath = options.projectPath || process.cwd();
  const skillsDir = path.join(basePath, '.agents', 'skills');
  const results: SkillOperationResult[] = [];

  for (const [skillName, template] of Object.entries(SHARED_SKILLS)) {
    const skillDir = path.join(skillsDir, skillName);
    const skillFilePath = path.join(skillDir, 'SKILL.md');

    const exists = fs.existsSync(skillFilePath);

    if (exists) {
      const existingContent = fs.readFileSync(skillFilePath, 'utf-8');

      if (isMohistGenerated(existingContent)) {
        const frontmatter = parseFrontmatter(template);
        const existingFrontmatter = parseFrontmatter(existingContent);

        if (frontmatter && existingFrontmatter &&
            frontmatter.name === existingFrontmatter.name &&
            frontmatter.description === existingFrontmatter.description) {
          const templateWithoutMarker = buildMarkedContent(template);
          if (existingContent === templateWithoutMarker) {
            results.push({ skill: skillName, result: 'unchanged' });
            continue;
          }
        }

        const newContent = buildMarkedContent(template);
        writeSkillFile(skillFilePath, newContent);
        results.push({ skill: skillName, result: 'updated' });
      } else {
        if (options.force) {
          const newContent = buildMarkedContent(template);
          writeSkillFile(skillFilePath, newContent);
          results.push({ skill: skillName, result: 'overwritten' });
        } else {
          results.push({
            skill: skillName,
            result: 'skipped-protected',
            reason: 'file exists and is not a Mohist-generated file',
          });
        }
      }
    } else {
      const content = buildMarkedContent(template);
      writeSkillFile(skillFilePath, content);
      results.push({ skill: skillName, result: 'created' });
    }
  }

  return results;
}

export function updateSharedAgentSkills(options: UpdateOptions = {}): SkillOperationResult[] {
  const basePath = options.projectPath || process.cwd();
  const skillsDir = path.join(basePath, '.agents', 'skills');
  const results: SkillOperationResult[] = [];

  for (const [skillName, template] of Object.entries(SHARED_SKILLS)) {
    const skillDir = path.join(skillsDir, skillName);
    const skillFilePath = path.join(skillDir, 'SKILL.md');

    const exists = fs.existsSync(skillFilePath);

    if (!exists) {
      const content = buildMarkedContent(template);
      writeSkillFile(skillFilePath, content);
      results.push({ skill: skillName, result: 'created' });
      continue;
    }

    const existingContent = fs.readFileSync(skillFilePath, 'utf-8');

    if (isMohistGenerated(existingContent)) {
      const frontmatter = parseFrontmatter(template);
      const existingFrontmatter = parseFrontmatter(existingContent);

      if (frontmatter && existingFrontmatter &&
          frontmatter.name === existingFrontmatter.name &&
          frontmatter.description === existingFrontmatter.description) {
        const templateWithoutMarker = buildMarkedContent(template);
        if (existingContent === templateWithoutMarker) {
          results.push({ skill: skillName, result: 'unchanged' });
          continue;
        }
      }

      const newContent = buildMarkedContent(template);
      writeSkillFile(skillFilePath, newContent);
      results.push({ skill: skillName, result: 'updated' });
    } else {
      results.push({
        skill: skillName,
        result: 'skipped-protected',
        reason: 'file exists and is not a Mohist-generated file',
      });
    }
  }

  return results;
}

export function getSharedSkillNames(): string[] {
  return Object.keys(SHARED_SKILLS);
}