import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const SOURCE_URL = 'https://models.dev';
const SNAPSHOT_FILE = path.join(__dirname, '..', 'src', 'config', 'models-snapshot.ts');

async function main() {
  const existingSnapshot = fs.existsSync(SNAPSHOT_FILE);

  let data: string;
  if (process.env.MODELS_DEV_API_JSON) {
    console.log(`Using MODELS_DEV_API_JSON: ${process.env.MODELS_DEV_API_JSON}`);
    data = fs.readFileSync(process.env.MODELS_DEV_API_JSON, 'utf-8');
  } else {
    console.log(`Fetching ${SOURCE_URL}/api.json...`);
    try {
      const result = await fetch(`${SOURCE_URL}/api.json`, {
        signal: AbortSignal.timeout(15000),
      });
      if (!result.ok) {
        throw new Error(`HTTP ${result.status}`);
      }
      data = await result.text();
    } catch (err) {
      if (existingSnapshot) {
        console.log(`Network error: ${err.message}`);
        console.log('Using existing snapshot, build continues.');
        return;
      }
      console.error(`Failed to fetch models.dev and no existing snapshot: ${err.message}`);
      process.exit(1);
    }
  }

  try {
    JSON.parse(data);
  } catch {
    console.error('Invalid JSON from models.dev');
    process.exit(1);
  }

  const output = `// @ts-nocheck
// Auto-generated by build.ts - do not edit
export const snapshot = ${data}
`;

  fs.writeFileSync(SNAPSHOT_FILE, output, { mode: 0o644 });
  console.log(`Generated ${path.relative(process.cwd(), SNAPSHOT_FILE)}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});